/**
 * TypeScript interfaces for Transformer architecture visualization.
 * 
 * These types match the semantic Parquet schema generated by extract_smollm.py
 * 
 * Tables:
 * 1. tensors.parquet        - Tensor catalog (~326 rows)
 * 2. tensor_stats.parquet   - Whole-tensor metrics (~326 rows)
 * 3. tensor_dims.parquet    - Per-output-dimension metrics (~976k rows)
 * 4. tensor_blocks.parquet  - Semantic block decomposition (~23k rows)
 * 5. tensor_block_topk.parquet - Sparse weight anchors (~370k rows)
 * 6. tensor_relations.parquet  - Semantic relations (~1k rows)
 */

// ============================================================================
// 1. Tensors - Tensor catalog
// ============================================================================

export type ModuleType = "embed" | "attn" | "mlp" | "norm" | "output";

export type TensorRole =
  // Global
  | "embed_tokens"
  | "final_norm"
  | "lm_head"
  // Per-layer norms
  | "input_norm"
  | "post_norm"
  // Attention projections
  | "q"
  | "k"
  | "v"
  | "o"
  // MLP projections
  | "gate"
  | "up"
  | "down";

export interface Tensor {
  tensor_id: string;           // Canonical ID: L{layer}.{module}.{role} e.g. "L12.attn.q"
  hf_name: string;             // HuggingFace param name
  layer: number | null;
  module: ModuleType;
  role: TensorRole;
  ndim: number;
  shape_0: number;
  shape_1: number | null;
  param_count: number;
  dtype: string;
  is_tied: boolean;
  tied_to_tensor_id: string | null;
}

// ============================================================================
// 2. Tensor Stats - Whole-tensor metrics
// ============================================================================

export interface TensorStats {
  tensor_id: string;
  fro_norm: number;      // Frobenius norm - drives tile brightness
  mean_abs: number;      // Mean absolute value
  std: number;           // Standard deviation
  p95_abs: number;       // 95th percentile absolute value
  p99_abs: number;       // 99th percentile absolute value
  zero_frac: number;     // Fraction of zeros
  min: number;           // Minimum value
  max: number;           // Maximum value
}

// ============================================================================
// 3. Tensor Dims - Per-output-dimension metrics (~976k rows)
// ============================================================================

export type HeadKind = "q_head" | "kv_head" | "none";

export interface TensorDim {
  tensor_id: string;
  layer: number;
  module: ModuleType;
  role: TensorRole;
  head_kind: HeadKind;
  head: number | null;   // 0-15 for q_head, 0-3 for kv_head, null for MLP
  dim: number;           // Output dimension index (0-127 within head, or 0-11007 for MLP)
  row_l2: number;        // L2 norm of this row
  row_mean_abs: number;  // Mean absolute value
  row_std: number;       // Standard deviation
  row_p95_abs: number;   // 95th percentile
  row_zero_frac: number; // Fraction of zeros
}

// ============================================================================
// 4. Tensor Blocks - Semantic block decomposition (~23k rows)
// ============================================================================

export interface TensorBlock {
  tensor_id: string;
  layer: number;
  module: ModuleType;
  role: TensorRole;
  head_kind: HeadKind;
  head: number | null;     // For Q/K/V blocks
  out_block: number | null; // For O blocks (0-15)
  in_block: number;        // Input block index (0-15)
  out_start: number;       // Output index range start
  out_end: number;         // Output index range end
  in_start: number;        // Input index range start
  in_end: number;          // Input index range end
  fro_norm: number;        // Frobenius norm of block
  mean_abs: number;
  std: number;
  p95_abs: number;
  row_gini: number;        // Gini coefficient of row norms (concentration)
  col_gini: number;        // Gini coefficient of column norms
}

// ============================================================================
// 5. Tensor Block TopK - Sparse weight anchors (~370k rows)
// ============================================================================

export interface TensorBlockTopK {
  tensor_id: string;
  layer: number;
  role: TensorRole;
  head: number | null;
  out_block: number | null;
  in_block: number;
  k: number;               // Number of top values stored (e.g., 32)
  row_idx: number[];       // Row indices of top-k values
  col_idx: number[];       // Column indices of top-k values
  value: number[];         // Actual weight values
}

// ============================================================================
// 6. Tensor Relations - Semantic relations (~1k rows)
// ============================================================================

export type RelationType = 
  | "feeds_into"        // e.g., input_norm → q/k/v
  | "projects_to"       // e.g., q/k/v → attention_op → o
  | "residual_adds_to"  // e.g., o/down → spine
  | "tied_to"           // e.g., lm_head → embed_tokens
  | "shares_kv";        // GQA: q_head → kv_head

export interface TensorRelation {
  src_tensor_id: string;
  dst_tensor_id: string;
  relation: RelationType;
  layer: number | null;
  note: string | null;
}

// ============================================================================
// Aggregated Data for Visualization
// ============================================================================

/** Aggregated head brightness: sum of row_l2 over dims */
export interface HeadAggregate {
  layer: number;
  head: number;
  total_l2: number;       // Sum of row_l2 across 128 dims
  avg_mean_abs: number;   // Average mean_abs
  max_p95_abs: number;    // Max p95_abs
}

/** Aggregated KV brightness: sum of row_l2 for K+V */
export interface KVAggregate {
  layer: number;
  kv_head: number;
  k_total_l2: number;
  v_total_l2: number;
  combined_l2: number;
}

/** Per-head in-block profile (16 values from tensor_blocks) */
export interface HeadBlockProfile {
  layer: number;
  head: number;
  in_block_norms: number[]; // 16 values: fro_norm per in_block
}

/** O-proj mixing signature (16x16 matrix) */
export interface OProjSignature {
  layer: number;
  matrix: number[][]; // 16x16: out_block × in_block(head_chunk)
}

// ============================================================================
// Visual Rendering Types
// ============================================================================

export interface VisualPosition {
  x: number;
  y: number; // Layer depth (vertical tower axis)
  z: number;
}

export interface VisualColor {
  r: number;
  g: number;
  b: number;
  alpha?: number;
}

/** Point data for GPU point cloud rendering */
export interface DimensionPoint {
  position: VisualPosition;
  size: number;          // From sqrt(row_l2)
  color: VisualColor;    // From row_p95_abs
  layer: number;
  head: number | null;
  dim: number;
  tensor_id: string;
}

// ============================================================================
// Hover Info Types
// ============================================================================

export interface TensorHoverInfo {
  type: "tensor";
  tensor_id: string;
  hf_name: string;
  shape: [number, number | null];
  param_count: number;
  stats: TensorStats;
}

export interface DimHoverInfo {
  type: "dim";
  tensor_id: string;
  layer: number;
  head: number | null;
  dim: number;
  row_l2: number;
  row_mean_abs: number;
  row_p95_abs: number;
  row_zero_frac: number;
}

export interface HeadHoverInfo {
  type: "head";
  layer: number;
  head: number;
  kv_group: number;
  aggregate: HeadAggregate;
  block_profile: number[];  // 16 in-block norms
}

export interface KVHoverInfo {
  type: "kv";
  layer: number;
  kv_head: number;
  serving_heads: number[]; // 4 Q heads that share this KV
  aggregate: KVAggregate;
}

export interface BlockHoverInfo {
  type: "block";
  tensor_id: string;
  layer: number;
  head: number | null;
  out_block: number | null;
  in_block: number;
  fro_norm: number;
  row_gini: number;
  col_gini: number;
  topk?: TensorBlockTopK;
}

export type HoverInfo = 
  | TensorHoverInfo 
  | DimHoverInfo 
  | HeadHoverInfo 
  | KVHoverInfo 
  | BlockHoverInfo 
  | null;

// ============================================================================
// Selection Types
// ============================================================================

export type SelectionType = "layer" | "head" | "kv_group" | "tensor_type" | "role" | null;

export interface Selection {
  type: SelectionType;
  value: number | string | null;
  layer?: number;
  head?: number;
  kv_group?: number;
  role?: TensorRole;
}
