// Sankeykey — minimal data layer. One CSV, one table, no crossfilter:
// the page exists to showcase the depth-expandable sankey on its own.

import { atom } from "jotai";
import * as vg from "@uwdata/vgplot";
import type { Coordinator } from "@uwdata/mosaic-core";
import { arrowFirstRow, arrowRows } from "../../../components/chartUtils";
import { localDuckDB } from "../../../components/duckdbLocal";
import { LoadingState } from "../../../types/loading";
import { categoryFor } from "../../../components/taxonomy";
import type { Category } from "../../../components/taxonomy";

// Must match MAX_TOOL_STEPS in extract_trajectories.py
export const MAX_DEPTH = 80;

// Flat projections (id, outcome, step_1..8) of the trajectory-atlas parquets,
// generated by extract_trajectories.py --flat-csv [--flat-csv-where]. CSV so
// the wasm core can read it without autoloading the parquet extension from
// a third-party CDN — the page is fully self-hosted.
export type SourceKey = "deepswe" | "hermes" | "deepseek-pi";

// `short` is the compact toggle label; `label` is the full descriptive name.
export const SOURCES: Record<
  SourceKey,
  { label: string; short: string; url: string }
> = {
  deepswe: {
    label: "DeepSWE · Kimi-K2",
    short: "deepswe",
    url: "/data/trajectory-atlas/deepswe-kimi-flat.csv",
  },
  hermes: {
    label: "Hermes · agent traces",
    short: "hermes",
    url: "/data/trajectory-atlas/hermes-flat.csv",
  },
  "deepseek-pi": {
    label: "DeepSeek-v4 · pi",
    short: "deepseek",
    url: "/data/trajectory-atlas/deepseek-pi-flat.csv",
  },
};

const STEP_COLS = Array.from({ length: MAX_DEPTH }, (_, i) => `step_${i + 1}`);

/** Depth stats: `ge[k-1]` = rollouts whose k-th step column is a real tool
 * (not the `(none)` sentinel); `paths[k-1]` = distinct tool sequences
 * through the first k calls — the diversity the sankey aggregates. */
export interface Survival {
  total: number;
  ge: number[];
  paths: number[];
}

// Primitive atoms — infra
export const loadingStateAtom = atom<LoadingState>({ status: "idle" });
export const coordinatorAtom = atom<Coordinator | null>(null);

// Primitive atoms — UI
export const depthAtom = atom(12);
export const playingAtom = atom(false);
export const sankeyActiveAtom = atom(false);
export const resetSignalAtom = atom(0);
/** Source whose table is live in DuckDB. The sankey remounts keyed on this,
 * so it only re-queries after the table swap completes. */
export const loadedSourceAtom = atom<SourceKey | null>(null);

// Computed once at init so the readout tracks slider drags synchronously.
export const survivalAtom = atom<Survival | null>(null);
export const legendCategoriesAtom = atom<Category[]>([]);

/** Deepest tool call present in the loaded dataset: the largest k where at
 * least one rollout makes a k-th call. Caps the slider at the data's real
 * depth, not the hard MAX_DEPTH column ceiling. */
export const maxDepthAtom = atom((get) => {
  const s = get(survivalAtom);
  if (!s || s.total <= 0) return MAX_DEPTH;
  let k = 1;
  for (let i = 0; i < s.ge.length; i++) if (s.ge[i] > 0) k = i + 1;
  return Math.min(MAX_DEPTH, Math.max(2, k));
});

async function loadSurvival(coord: Coordinator): Promise<Survival> {
  const ge = STEP_COLS.map(
    (c, i) =>
      `COUNT(*) FILTER (WHERE ${c} IS NOT NULL AND ${c} <> '(none)') AS ge_${i + 1}`,
  );
  const paths = STEP_COLS.map(
    (_, i) =>
      `COUNT(DISTINCT concat_ws('→', ${STEP_COLS.slice(0, i + 1).join(", ")})) AS paths_${i + 1}`,
  );
  const r = await coord.query(`
    SELECT COUNT(*) AS total, ${ge.join(", ")}, ${paths.join(", ")}
    FROM trajectories
  `);
  const row = arrowFirstRow(r);
  return {
    total: Number(row?.total ?? 0),
    ge: STEP_COLS.map((_, i) => Number(row?.[`ge_${i + 1}`] ?? 0)),
    paths: STEP_COLS.map((_, i) => Number(row?.[`paths_${i + 1}`] ?? 0)),
  };
}

async function loadLegendCategories(coord: Coordinator): Promise<Category[]> {
  const r = await coord.query(`
    SELECT DISTINCT unnest([${STEP_COLS.join(", ")}]) AS tool
    FROM trajectories
  `);
  const cats = new Set<Category>();
  for (const row of arrowRows(r)) {
    const tool = row.tool;
    if (typeof tool !== "string" || !tool || tool === "(none)") continue;
    cats.add(categoryFor(tool));
  }
  return Array.from(cats);
}

async function loadTable(coord: Coordinator, src: SourceKey): Promise<void> {
  const url = `${window.location.origin}${SOURCES[src].url}`;
  await coord.exec(`DROP TABLE IF EXISTS trajectories`);
  await coord.exec(`
    CREATE TABLE trajectories AS
    SELECT * FROM read_csv('${url}', header = true, all_varchar = true)
  `);
}

/** Swap the live table to another source, then refresh the derived stats.
 * The chart keeps showing the old source until `loadedSourceAtom` flips. */
export const switchSourceAtom = atom(null, async (get, set, src: SourceKey) => {
  const coord = get(coordinatorAtom);
  if (!coord || get(loadedSourceAtom) === src) return;

  try {
    set(playingAtom, false);
    await loadTable(coord, src);
    const stats = await loadStats(coord);
    set(survivalAtom, stats.survival);
    set(legendCategoriesAtom, stats.categories);
    // Clamp depth so it never exceeds the new dataset's real max.
    set(depthAtom, (d) => Math.min(d, get(maxDepthAtom)));
    set(resetSignalAtom, (n) => n + 1);
    set(loadedSourceAtom, src);
  } catch (err) {
    console.error("Sankeykey source switch failed:", err);
  }
});

async function loadStats(coord: Coordinator) {
  const [survival, categories] = await Promise.all([
    loadSurvival(coord),
    loadLegendCategories(coord),
  ]);
  return { survival, categories };
}

export const initializeSankeykeyAtom = atom(null, async (get, set) => {
  if (get(coordinatorAtom)) return;
  const src: SourceKey = "deepswe";

  try {
    set(loadingStateAtom, { status: "initializing" });
    const connector = vg.wasmConnector({ duckdb: await localDuckDB() });
    // Local coordinator only — never registered as the vgplot global, so
    // visiting this page can't clobber other demos' singleton.
    const coord = new vg.Coordinator(connector, {
      cache: false,
      preagg: { enabled: false },
    });
    set(coordinatorAtom, coord);

    set(loadingStateAtom, {
      status: "loading-parquet",
      message: SOURCES[src].label,
    });
    await loadTable(coord, src);

    set(loadingStateAtom, { status: "creating-tables", table: "stats" });
    const stats = await loadStats(coord);
    set(survivalAtom, stats.survival);
    set(legendCategoriesAtom, stats.categories);
    set(loadedSourceAtom, src);
    set(loadingStateAtom, { status: "ready" });
  } catch (err) {
    console.error("Sankeykey init failed:", err);
    set(loadingStateAtom, {
      status: "error",
      message: err instanceof Error ? err.message : "Unknown error",
    });
  }
});

initializeSankeykeyAtom.onMount = (trigger) => {
  trigger();
};
